apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - server-deployment.yaml
  - server-service.yaml
  - client-deployment.yaml
  - client-service.yaml

images:
  - name: IMAGE_PLACEHOLDER_SERVER
    newName: IMAGE_PLACEHOLDER_SERVER
    newTag: latest
  - name: IMAGE_PLACEHOLDER_CLIENT
    newName: IMAGE_PLACEHOLDER_CLIENT
    newTag: latest
